### ISSUE TITLE
关于编译脚本的一些建议

### ISSUE THREAD

**Issue by arror** [yiguous/libxray#1]
https://github.com/yiguous/libxray/blob/0ad0717b70b088ff628b917dade43dfbe0a60a9a/build.sh#L11

1. target应该可以同时指定不同的架构，最低支持版本，以及优化选项。
2. 支持模拟器架构可以方便开发者构建UI。
 
例如
gomobile bind -o ./XrayKit.xcframework -target=ios,iossimulator,macos -iosversion=12.0 -ldflags="-s -w" -v ./

**Comment by yiguous** [comment]
感谢建议，已做部分优化。
